.TH "C:/Users/Leon Franke/Desktop/pse2019-gruppe09-master/include Directory Reference" 3 "Mon Jun 10 2019" "Dokumentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Leon Franke/Desktop/pse2019-gruppe09-master/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhttp_base64\&.h\fP"
.br
.RI "This file provides functions to encode and decode c-strings/char pointers from and to base64 encoded text\&. "
.ti -1c
.RI "file \fBhttp_error\&.h\fP"
.br
.RI "File contains functions fot error handling\&. "
.ti -1c
.RI "file \fBhttp_fileIO\&.h\fP"
.br
.RI "All file functions required for reading, writing, etc\&. are accommodated here\&. "
.ti -1c
.RI "file \fBhttp_parser\&.h\fP"
.br
.RI "This file provides all functions for processing the incoming requests, from reading everything into a struct, to generating an answer\&. "
.ti -1c
.RI "file \fBhttp_security\&.h\fP"
.br
.ti -1c
.RI "file \fBhttp_server\&.h\fP"
.br
.ti -1c
.RI "file \fBhttp_settings\&.h\fP"
.br
.ti -1c
.RI "file \fBhttp_status\&.h\fP"
.br
.RI "This is where all status messages are defined and set as required\&. "
.ti -1c
.RI "file \fBhttp_string\&.h\fP"
.br
.RI "This file contains all string functions that are currently needed and may need later\&. "
.ti -1c
.RI "file \fBhttp_utils\&.h\fP"
.br
.RI "This file provides all functions that are needed for utility\&. "
.in -1c
