.TH "credentialArray" 3 "Mon Jun 10 2019" "Dokumentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
credentialArray
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <http_security\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhttp_credentials\fP ** \fBcredential_array\fP"
.br
.ti -1c
.RI "size_t \fBcredentialCount\fP"
.br
.ti -1c
.RI "size_t \fBmaxCredentialCount\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBhttp_credentials\fP** credential_array"

.SS "size_t credentialCount"

.SS "size_t maxCredentialCount"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentation from the source code\&.
