.TH "credentials" 3 "Mon Jun 10 2019" "Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
credentials
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstring\fP * \fBuser\fP"
.br
.RI "The username to store\&. "
.ti -1c
.RI "\fBstring\fP * \fBpassword\fP"
.br
.RI "The password corresponding to the username\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Documentation from the source code\&.
