.TH "credentialArray" 3 "Mon Jun 10 2019" "Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
credentialArray
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhttp_credentials\fP ** \fBcredential_array\fP"
.br
.RI "An array/pointer of credential pointers\&. "
.ti -1c
.RI "size_t \fBcredentialCount\fP"
.br
.RI "The currently stored credentials\&. Should always be <= maxCredentialCount, otherwise an overflow will happen\&. "
.ti -1c
.RI "size_t \fBmaxCredentialCount\fP"
.br
.RI "The maximum number of credentials to store, and so to allocate\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Documentation from the source code\&.
