.TH "http_credential_array" 3 "Mon Jun 10 2019" "Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
http_credential_array \- Used to store an array(pointer) to credential pointers together with the count of them\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <http_security\&.h>\fP
.SH "Detailed Description"
.PP 
Used to store an array(pointer) to credential pointers together with the count of them\&. 

New credentials should only be added by calling credential_array_add(), to be sure to not overflow the array\&. The memory for all credentials up to maxCredentialCount is allocated when creating a new one by calling new_httpCredentialArray()\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Documentation from the source code\&.
