.TH "C:/Users/Leon Franke/Desktop/pse2019-gruppe09-master/include/http_fileIO.h" 3 "Mon Jun 10 2019" "Dokumentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Leon Franke/Desktop/pse2019-gruppe09-master/include/http_fileIO.h \- All file functions required for reading, writing, etc\&. are accommodated here\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'http_string\&.h'\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstring\fP * \fBtoRealPath\fP (\fBstring\fP *path)"
.br
.ti -1c
.RI "char \fBisInDocumentRoot\fP (\fBstring\fP *filepath, \fBstring\fP *root)"
.br
.ti -1c
.RI "size_t \fBgetFilesize\fP (\fBstring\fP *filepath)"
.br
.ti -1c
.RI "void * \fBloadFileToBuffer\fP (\fBstring\fP *filepath)"
.br
.ti -1c
.RI "\fBstring\fP * \fBgetMimeType\fP (\fBstring\fP *path)"
.br
.ti -1c
.RI "\fBstring\fP * \fBgetMimeEncoding\fP (\fBstring\fP *path)"
.br
.in -1c
.SH "Detailed Description"
.PP 
All file functions required for reading, writing, etc\&. are accommodated here\&. 

Also here you can define the different filepaths and document roots\&. 
.SH "Function Documentation"
.PP 
.SS "size_t getFilesize (\fBstring\fP * filepath)"
Returns the size of a file\&.
.PP
\fBParameters:\fP
.RS 4
\fIfilepath\fP The path, the file lays in\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The size of the file at the given path\&. 0 if file is empty or not available\&. 
.RE
.PP

.SS "\fBstring\fP* getMimeEncoding (\fBstring\fP * path)"
Returns the string containing the content/mime encoding of the resource\&. Returns an empty string with lenth 0, if information could not be found\&.
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The path to the resource\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string containing the MIME-Encoding of the resource\&. Empty string if information was not found\&. 
.RE
.PP

.SS "\fBstring\fP* getMimeType (\fBstring\fP * path)"
Returns the string containing the content/mime type of the resource\&. Returns an empty string with lenth 0, if information could not be found\&.
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The path to the resource\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string containing the MIME-Type of the resource\&. Empty string if information was not found\&. 
.RE
.PP

.SS "char isInDocumentRoot (\fBstring\fP * filepath, \fBstring\fP * root)"
Checks if a path lays in the document root\&.
.PP
\fBParameters:\fP
.RS 4
\fIfilepath\fP The path to check if it lays in the document root\&. 
.br
\fIroot\fP The document path root to check\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
0 if the path is not in the document root, 1 if it is in document root\&. 
.RE
.PP

.SS "void* loadFileToBuffer (\fBstring\fP * filepath)"
Loads a file at a given path into a buffer and returns it\&.
.PP
\fBParameters:\fP
.RS 4
\fIfilepath\fP The path of the file to be loaded\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The file in a buffer\&. NULL if file was not found\&. 
.RE
.PP

.SS "\fBstring\fP* toRealPath (\fBstring\fP * path)"
Converts a path with /\&.\&./ etc to an absolute path\&. If file is not found, an empty string is returned\&. (Length = 0)
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The path to convert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The converted, absolute path\&. Returns an empty string if path is not found\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentation from the source code\&.
