.TH "http_response" 3 "Mon Jun 10 2019" "Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
http_response \- Used to bundle all information about a response\&. Contains all header fields, used by the program and can be expanded to the needs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <http_parser\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstring\fP * \fBhttp_version\fP"
.br
.RI "The HTTP version, that the response has\&. In general it will always be HTTP/1\&.1\&. "
.ti -1c
.RI "\fBstring\fP * \fBstatus\fP"
.br
.RI "The HTTP status code, wit a textual description\&. For example '200 OK'\&. "
.ti -1c
.RI "\fBstring\fP * \fBserver\fP"
.br
.RI "A textual description of the server itself\&. This can be anything\&. "
.ti -1c
.RI "\fBstring\fP * \fBcontent_type\fP"
.br
.RI "The MIME-Type of the content that is sent\&. "
.ti -1c
.RI "\fBstring\fP * \fBcontent_encoding\fP"
.br
.RI "The encoding format of the content\&. "
.ti -1c
.RI "size_t \fBcontent_length\fP"
.br
.RI "The length of the sent content in bytes\&. "
.ti -1c
.RI "char \fBauth_required\fP"
.br
.RI "This is a flag to set if the client has to authorize\&. If it is not set to 0, the response string will contain the information for the client that it has to authenticate\&. "
.ti -1c
.RI "void * \fBcontent\fP"
.br
.RI "The actual content that should be sent\&. Can contain anything casted to a void pointer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Used to bundle all information about a response\&. Contains all header fields, used by the program and can be expanded to the needs\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Documentation from the source code\&.
