.TH "C:/Users/Leon Franke/Desktop/pse2019-gruppe09-master/include/http_error.h" 3 "Mon Jun 10 2019" "Dokumentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Leon Franke/Desktop/pse2019-gruppe09-master/include/http_error.h \- File contains functions fot error handling\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBerror\fP (char *message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
File contains functions fot error handling\&. 


.SH "Function Documentation"
.PP 
.SS "void error (char * message)"
Prints a message to the standard error output and exits\&.
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP The message to print before exiting\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentation from the source code\&.
