.TH "C:/Users/Leon Franke/Desktop/pse2019-gruppe09-master/README.md" 3 "Mon Jun 10 2019" "Dokumentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Leon Franke/Desktop/pse2019-gruppe09-master/README.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentation from the source code\&.
