.TH "string" 3 "Mon Jun 10 2019" "Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBlen\fP"
.br
.RI "The length in bytes of the string\&. This is without a null terminator, because we dont use one!!! "
.ti -1c
.RI "char * \fBstr\fP"
.br
.RI "The actual bytes/characters of the string\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Documentation from the source code\&.
