.TH "string" 3 "Mon Jun 10 2019" "Dokumentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <http_string\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "char * \fBstr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t len"

.SS "char* str"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dokumentation from the source code\&.
